// All dates are INCLUSIVE (both start and end are actual calendar days).
// The app converts end dates to exclusive when feeding FullCalendar.

const COURTS = {
  'supreme-court': {
    id: 'supreme-court',
    name: 'Supreme Court of India',
    shortName: 'SC',
    year: 2026,
    color: '#1565C0',
    textColor: '#ffffff',
    holidays: [
      { name: 'New Year Holidays',                    start: '2026-01-01', end: '2026-01-02' },
      { name: 'Makar Sankranti / Magh Bihu / Pongal', start: '2026-01-14' },
      { name: 'Republic Day',                         start: '2026-01-26' },
      { name: 'Holi Holidays',                        start: '2026-03-02', end: '2026-03-07' },
      { name: 'Id-ul-Fitr',                           start: '2026-03-21', note: 'Subject to moon visibility' },
      { name: 'Ram Navami',                           start: '2026-03-26' },
      { name: 'Local Holiday',                        start: '2026-03-27' },
      { name: 'Local Holiday',                        start: '2026-03-30' },
      { name: 'Mahavir Jayanti',                      start: '2026-03-31' },
      { name: 'Good Friday',                          start: '2026-04-03' },
      { name: 'Budha Purnima',                        start: '2026-05-01' },
      { name: 'Id-ul-Zuha (Bakrid)',                  start: '2026-05-27', note: 'Subject to moon visibility' },
      { name: 'Muharram',                             start: '2026-06-26', note: 'Subject to moon visibility' },
      { name: 'Independence Day',                     start: '2026-08-15' },
      { name: 'Milad-un-Nabi / Id-e-Milad',           start: '2026-08-26', note: 'Subject to moon visibility' },
      { name: 'Raksha Bandhan',                       start: '2026-08-28' },
      { name: 'Janmashtami',                          start: '2026-09-04' },
      { name: 'Ganesh Chaturthi',                     start: '2026-09-14' },
      { name: "Mahatma Gandhi's Birthday",            start: '2026-10-02' },
      { name: 'Dussehra Holidays',                    start: '2026-10-19', end: '2026-10-24' },
      { name: 'Diwali Holidays',                      start: '2026-11-09', end: '2026-11-14' },
      { name: "Guru Nanak's Birthday",                start: '2026-11-24' },
      { name: 'Christmas & New Year Holidays',        start: '2026-12-21', end: '2027-01-01' },
    ],
    vacations: [
      {
        name: 'Summer Recess (Partial Working Days)',
        start: '2026-06-01',
        end: '2026-07-12',
        type: 'partial',
        note: 'Partial court working days Jun 1 – Jul 12. Full court resumes Jul 13. Registry remains open (except Sat/Sun/holidays). Registry open on last Saturday Jul 11.'
      },
    ],
    specialDays: [],
  },

  'delhi-hc': {
    id: 'delhi-hc',
    name: 'Delhi High Court',
    shortName: 'DHC',
    year: 2026,
    color: '#2E7D32',
    textColor: '#ffffff',
    holidays: [
      { name: "New Year's Day",                start: '2026-01-01' },
      { name: 'Republic Day',                  start: '2026-01-26' },
      { name: 'Maha Shivratri',                start: '2026-02-15', note: 'Falls on Sunday' },
      { name: 'Holi',                          start: '2026-03-04' },
      { name: 'Id-ul-Fitr',                    start: '2026-03-21', note: 'Subject to moon visibility' },
      { name: 'Ram Navami',                    start: '2026-03-26' },
      { name: 'Mahavir Jayanti',               start: '2026-03-31' },
      { name: 'Good Friday',                   start: '2026-04-03' },
      { name: 'Budha Purnima',                 start: '2026-05-01' },
      { name: 'Id-ul-Zuha (Bakrid)',           start: '2026-05-27', note: 'Subject to moon visibility' },
      { name: 'Muharram',                      start: '2026-06-26', note: 'Subject to moon visibility' },
      { name: 'Independence Day',              start: '2026-08-15' },
      { name: 'Milad-un-Nabi / Id-e-Milad',   start: '2026-08-26', note: 'Subject to moon visibility' },
      { name: 'Raksha Bandhan',                start: '2026-08-28' },
      { name: 'Janmashtami',                   start: '2026-09-04' },
      { name: "Mahatma Gandhi's Birthday",     start: '2026-10-02' },
      { name: 'Mahashtami',                    start: '2026-10-19' },
      { name: 'Dussehra',                      start: '2026-10-20' },
      { name: "Maharishi Valmiki's Birthday",  start: '2026-10-26' },
      { name: 'Diwali (Deepavali)',            start: '2026-11-08', note: 'Falls on Sunday' },
      { name: 'Govardhan Puja',               start: '2026-11-09' },
      { name: 'Bhai Duj',                     start: '2026-11-11' },
      { name: "Guru Nanak's Birthday",         start: '2026-11-24' },
      { name: 'Christmas Day',                 start: '2026-12-25' },
    ],
    vacations: [
      {
        name: 'Summer Vacation',
        start: '2026-06-01',
        end: '2026-06-30',
        type: 'full',
        note: 'High Court remains closed. Subordinate Courts summer vacation: Jun 15 – Jun 30.'
      },
      {
        name: 'Winter Vacation',
        start: '2026-12-26',
        end: '2026-12-31',
        type: 'full',
        note: 'High Court remains closed (both days inclusive). Subordinate Courts also closed Dec 26 – Dec 31.'
      },
    ],
    specialDays: [
      { name: 'Court Sitting Saturday', start: '2026-07-25', note: 'Special sitting day (normally non-working)' },
      { name: 'Court Sitting Saturday', start: '2026-09-26', note: 'Special sitting day (normally non-working)' },
      { name: 'Court Sitting Saturday', start: '2026-11-28', note: 'Special sitting day (normally non-working)' },
    ],
  },
};
